#!/bin/sh
frames_count=$(identify $1 | tail -1 | cut -d "[" -f2 - | cut -d "]" -f1 -)
delay=$(identify -verbose $1[0] | grep Delay | gawk 'match($0, /Delay: ([0-9]*)x[0-9]*/, arr) {print arr[1]}')

echo 'Gif info:'
echo "frames_count: $frames_count"
echo "delay: $delay"
