#!/bin/bash

rm config/secrets.yml
environments=( "development" "test" )

for env in "${environments[@]}"
do
	key=$(rake secret)
	echo "$env:
  secret_key_base: ${key}
" >> config/secrets.yml
done

echo 'production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
' >> config/secrets.yml
